### ISSUE TITLE
Version 0.5.0 presents itself as 0.4.2

### ISSUE THREAD

**Issue by vitorgalvao** [draios/sysdig-inspect#100]
If we download version 0.5.0 from https://download.sysdig.com/stable/sysdig-inspect/sysdig-inspect-0.5.0-mac.dmg and do a Get Info (<kbd>⌘</kbd><kbd>I</kbd>) or inspect its `Info.plist`, we’ll see the version in the app is still 0.4.2.

**Comment by core-code** [comment]
i can confirm the problem

**Comment by vitorgalvao** [comment]
No longer relevant, as the current release (`0.10.1`) has the correct version.
