### ISSUE TITLE
Adding to caskroom

### ISSUE THREAD

**Issue by jacobbednarz** [draios/sysdig-inspect#11]
Just a FYI that I've kicked off the process to get `sysdig-inspect` added to caskroom via caskroom/homebrew-cask#39062.

**Comment by davideschiera** [comment]
Hey @jacobbednarz that sounds great!

Let me know if you need any help for it ;-)

**Comment by jacobbednarz** [comment]
This has landed. `brew cask install sysdig-inspector` away!

**Comment by davideschiera** [comment]
Sweet!

Just to double check, is it `sysdig-inspect` or `sysdig-inspector`? Just because the former would be the one :-)

Thanks!

**Comment by davideschiera** [comment]
Just verified, works perfectly. Thanks a lot for the help here!

**Comment by jacobbednarz** [comment]
Apologies, I did use both when I actually meant the first one. Are you :cool: with it being `sysdig-inspect`?

**Comment by davideschiera** [comment]
<img width="963" alt="screenshot 2017-09-27 20 24 42" src="https://user-images.githubusercontent.com/5033993/30948180-056ab490-a3c3-11e7-96a6-280d6a30cd07.png">

It's all good ;-) The correct name is Sysdig Inspect, so it's perfect.

Out of curiosity, what's the best practice to keep the cask definition up-to-date when a new release is available?

**Comment by jacobbednarz** [comment]
If you fork the `homebrew-cask` and make the changes to the formula, you should be good to go. caskroom/homebrew-cask#39055 have an example of updating a formula.
Their contributing guidelines are pretty good for what steps you need to take when opening a PR too.

**Comment by davideschiera** [comment]
Perfect! As we'll probably create several releases in the next few weeks, is there a why to let the formula refer to the latest version available at any given time? Or is it better to update the formula less often (e.g. once every other week or so)?

**Comment by jacobbednarz** [comment]
I did originally attempt this in [4a6530a](https://github.com/caskroom/homebrew-cask/pull/39062/commits/4a6530a6b7c7f6c4f0020e6a98fad3c548598316) however the review bot  updated it to be a specific version (which is pretty amazing considering it found the version, etc on it's own!). Perhaps you could have a look and see how it goes about finding that version and seeing if you could side step it? I've only done a few casks myself and versions have always been pretty easy to maintain and quickly merged so it hasn't really been a big deal.

**Comment by davideschiera** [comment]
Makes sense. It's ok for now to point to specific versions. Ultimately, the app itself should have an auto-update mechanisms (like browsers) so it wouldn't be a big problem.

Thanks again for the help ;-)
