### ISSUE TITLE
Search bar loses focus as soon as typing is stopped

### ISSUE THREAD

**Issue by ApsOps** [draios/sysdig-inspect#16]
"It seems that the focus is set to the table/stream after data loads so that we can use arrows to move up and down in the list. But this doesn't really play nice with changing data configuration and loading data again."

**Comment by davideschiera** [comment]
Fixed with #25. Will be merged to `dev` likely by tomorrow.

**Comment by davideschiera** [comment]
Fixed with https://github.com/draios/sysdig-inspect/releases/tag/0.2.0.
