### ISSUE TITLE
sysdig-inspect can not handle scaps from sysdig 0.21.0

### ISSUE THREAD

**Issue by guardiande** [draios/sysdig-inspect#34]
I recently upgraded sysdig 0.21.0 on Ubuntu 16.04. When I try to open scaps from 0.21.0 in sysdig-inspect 0.2.0 nothing is displayed. csysdig works.

Is this a known issue?

Original issue: draios/sysdig#1099

**Comment by davideschiera** [comment]
The issue should be fixed with https://github.com/draios/sysdig-inspect/releases/tag/0.3.0.

Let me know if it works now on your end too. Thanks!

**Comment by guardiande** [comment]
Thanks, the new release fixed it. 👍
