### ISSUE TITLE
docker pull sysdig/sysdig-inspect

### ISSUE THREAD

**Issue by preachermanx** [draios/sysdig-inspect#59]
Tag is missing (Perhaps intentionally?) for `:latest`. 
So  `docker pull sysdig/sysdig-inspect` by the listed docker usage method fails.

Of course, `docker pull sysdig/sysdig-inspect:0.4.2.7-dev` specific versions work as expected.

**Comment by davideschiera** [comment]
I literally just edited the "publish" script to create both `:latest` and `:dev` tags: https://github.com/draios/sysdig-inspect/pull/57/commits/60cc5b92326d5cfd03015cd0d980a942a85868a8

I was actually getting rid of all the `:x.y.z-dev` tags and keep a single `:dev` tag instead: Would this work as well?
