### ISSUE TITLE
Binds a Global hotkey on ⌘R and ⌘+Shift+I - disabling using keyboard to open dev tools or refresh in any browser while Inspect is open

### ISSUE THREAD

**Issue by donaldguy** [draios/sysdig-inspect#8]
While I have Sysdig Inspect open but not focused, attempting to refresh a separate chrome window via keyboard shortcut causes Sysdig Inspect to refresh and my local window not to

closing sysdig-inspect allows other chromes to refresh again

**Comment by donaldguy** [comment]
Cause

https://github.com/draios/sysdig-inspect/blob/71ec3a55632d3682991f6379afd8810487c1053a/ember-electron/main.js#L75-L83
```
    // Register a shortcuts for open devTools
    globalShortcut.register('CommandOrControl+Shift+I', () => {
        mainWindow.toggleDevTools();
    });

    // Register a shortcuts for reload page
    globalShortcut.register('CommandOrControl+R', () => {
        mainWindow.reload();
    });
```

**Comment by davideschiera** [comment]
Thanks for reporting the issue! I'd remove the shortcuts for now and then figure out a better way to deal with it. Sounds good?

**Comment by donaldguy** [comment]
yeah this is expected behavior for globalShortcut

https://electron.atom.io/docs/api/global-shortcut/

Looks like better practice is just to expose menu items with affiliated shortcuts
https://electron.atom.io/docs/tutorial/keyboard-shortcuts/

**Comment by davideschiera** [comment]
Sounds reasonable. Do you want to submit a PR for it? Otherwise I'll get it done in the next few hours. Thanks again!

**Comment by davideschiera** [comment]
The fix will be included in the next release, expected later today or tomorrow.

@donaldguy Thanks again for reporting the issue!
